// FD Module: MODULE1
// Auto-generated by FD Generator v1.0.0

module FD_MODULE1 (
    input  wire [31:0] fd_awaddr_from_core_crg,
    output wire [31:0] fd_awaddr_to_module2,
    input  wire [0:0] fd_awvalid_from_core_crg,
    output wire [0:0] fd_awvalid_to_module2,
    input  wire [0:0] fd_awready_from_core_crg,
    output wire [0:0] fd_awready_to_module2
);

    assign fd_awaddr_to_module2 = fd_awaddr_from_core_crg;
    assign fd_awvalid_to_module2 = fd_awvalid_from_core_crg;
    assign fd_awready_to_module2 = fd_awready_from_core_crg;

endmodule
