// FD Module: MODULE2
// Auto-generated by FD Generator v1.0.0

module FD_MODULE2 (
    input  wire [31:0] fd_awaddr_from_module1,
    output wire [31:0] fd_awaddr_to_module3,
    input  wire [0:0] fd_awvalid_from_module1,
    output wire [0:0] fd_awvalid_to_module3,
    input  wire [0:0] fd_awready_from_module1,
    output wire [0:0] fd_awready_to_module3
);

    assign fd_awaddr_to_module3 = fd_awaddr_from_module1;
    assign fd_awvalid_to_module3 = fd_awvalid_from_module1;
    assign fd_awready_to_module3 = fd_awready_from_module1;

endmodule
